camel-tooling/camel-idea-plugin

- pom.xml
A minor mistake was introduced when converting to maven build that it didn't include all resources
> Fix an issue with icons was not included in the build

- camel-idea-plugin/src/main/java/org/apache/camel/idea/annotator/AbstractCamelAnnotator.java
at org.apache.camel.idea.annotator.AbstractCamelAnnotator.accept(AbstractCamelAnnotator.java:66)
at org.apache.camel.idea.annotator.AbstractCamelAnnotator.annotate(AbstractCamelAnnotator.java:49)
at org.apache.camel.idea.annotator.CamelEndpointAnnotator.annotate(CamelEndpointAnnotator.java:45)
at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.a(DefaultHighlightVisitor.java:139)
at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:102)
at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:367)
at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:306)
at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.a(GeneralHighlightingPass.java:326) …
> fix NullPointerException in AbstractCamelAnnotator.java

- camel-idea-plugin/src/test/java/org/apache/camel/idea/CamelLightCodeInsightFixtureTestCaseIT.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/documentation/CamelSmartCompletionDocumentationTestIT.java
- camel-idea-plugin/src/test/resources/testData/documentation/XmlCamelRouteQuickDocCaretAtTheEndTestData.xml
- camel-idea-plugin/src/test/resources/testData/documentation/XmlCamelRouteQuickDocCaretOnAmpTestData.xml
Added unit test for documentation popup for routes that contains &amp;
@davsclaus , @fharms I've noticed in the tests many occurrences of
`// this does not work with <caret> in the source code`
`// PsiElement element = myFixture.getElementAtCaret();`
To fix that i've added the `CamelLightCodeInsightFixtureTestCaseIT.getElementAtCaret` method. Let me know if that fixes the issue.
> Added unit test for quick documentation popup

- camel-idea-plugin/src/main/java/org/apache/camel/idea/gutter/CamelRouteLineMarkerProvider.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/gutter/GutterPsiElementListCellRenderer.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/gutter/GutterTestUtil.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/gutter/JavaCamelRouteLineMarkerProviderTestIT.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/gutter/MultiLanguageCamelRouteLineMarkerProviderTestIT.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/gutter/XmlCamelRouteLineMarkerProviderTestIT.java
- camel-idea-plugin/src/test/resources/testData/JavaCamelRouteLineMarkerProviderTestData.java
- camel-idea-plugin/src/test/resources/testData/XmlCamelRouteLineMarkerProviderTestData.xml
First version of the navigation that suports Java literals and XML only. The issue #242 is still not solved so i did a workaround to filter out everything that is not a literal for Java.
> #240 Added gutter route navigation from/to Java/XML

- camel-idea-plugin/src/main/java/org/apache/camel/idea/annotator/AbstractCamelAnnotator.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/CamelContributor.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/CamelSmartCompletionEndpointOptions.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/extension/CamelEndpointSmartCompletionExtension.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/inspection/AbstractCamelInspection.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/intention/CamelAddEndpointIntention.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/util/IdeaUtils.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/completion/JavaEndpointSmartCompletionTestIT.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/completion/PropertyEndpointSmartCompletionTestIT.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/completion/XmlEndpointSmartCompletionTestIT.java
This is the first batch of multi line support for code completion, if you split endpoint uri over multiple lines the code completion will still work
```java
from("timer:trigger?repeatCount=10" +
"&fixedRate=false&bridgeErrorHandler=false" +
"&daemon=false" +
"&period=10&delay=1000")
```
The validation is not tested in depth, but a quick test shows it worked in the cases I tried. 
Since this required changes in some of the shared methods I want to push this to avoid too many conflicts. The code is in a good shape and multiple tests cases is added, but after it's merged I will properly use some time to clean it up a bit and test validation more
> Multiline completion support

- camel-idea-plugin/pom.xml
- camel-idea-plugin/src/test/java/org/apache/camel/idea/util/CamelRouteSearchScopeTest.java
Refactored pom.xml to allow to pass the unit test that fails in Maven but works in IntelliJ. 
Apprently the JVM properties were owevritten, changed the `<argLine>` as suggested here:
http://maven.apache.org/surefire/maven-surefire-plugin/faq.html#late-property-evaluation
>  Refactoring for surefire plugin

- camel-idea-plugin/src/main/java/org/apache/camel/idea/annotator/AbstractCamelAnnotator.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/annotator/CamelEndpointAnnotator.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/annotator/CamelSimpleAnnotator.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/CamelContributor.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/CamelSmartCompletionEndpointOptions.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/inspection/AbstractCamelInspection.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/intention/CamelAddEndpointIntention.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/util/IdeaUtils.java
- camel-idea-plugin/src/main/resources/META-INF/plugin.xml
- camel-idea-plugin/src/test/java/org/apache/camel/idea/annotator/CamelEndpointAnnotatorTestIT.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/annotator/CamelSimpleAnnotatorTestIT.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/completion/JavaEndpointSmartCompletionTestIT.java
This add basic support for multi line endpoint validation and multi line simple validation.
For other languges this feature is still missing and will require little more because we can't utilize the Scala PSI classes since the camel plug-in dosen't have a required dependency on other languges
> Multiline validation support

- camel-idea-plugin/src/main/java/org/apache/camel/idea/service/CamelService.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/service/CamelServiceTestIT.java
fixes #294
Considers also startIdx when checking for version presence
> Fixed version presence check in CamelService.scanForCamelProject 

- camel-idea-plugin/src/main/java/org/apache/camel/idea/util/CamelIdeaUtils.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/util/IdeaUtilsSkipEndointValidationTestIT.java
Following elements are skipped for endpoint validation
- ActiveMQComponent.activeMQComponent factory method
- ActiveMQXAConnectionFactory constructor
> Additional checks to skip endpoint validation for ActiveMQ brokerURL

- camel-idea-plugin/src/main/java/org/apache/camel/idea/annotator/CamelEndpointAnnotator.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/CamelContributor.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/inspection/AbstractCamelInspection.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/service/CamelService.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/service/QueryUtils.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/util/CamelIdeaUtils.java
- readme.md
we should keep an eye of dependencies between packages to avoid an unmaintainable-big-ball-of-mud-plugin. So I used structure101 to analyze dependencies between packages/classes and moved some methods to another location.
Please let me know if it doesn't make sense to move these methods to these classes.
> Remove cyclic dependencies between packages

- camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/contributor/CamelContributor.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/contributor/CamelGroovyReferenceContributor.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/contributor/CamelJavaReferenceContributor.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/contributor/CamelKotlinReferenceContributor.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/contributor/CamelPropertiesOrYamlFileReferenceContributor.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/contributor/CamelPropertyPlaceholderReferenceContributor.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/contributor/CamelScalaReferenceContributor.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/contributor/CamelXmlReferenceContributor.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/endpoint/CamelSmartCompletionEndpointOptions.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/endpoint/CamelSmartCompletionEndpointValue.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/extension/CamelCompletionExtension.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/extension/CamelEndpointSmartCompletionExtension.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/service/CamelCatalogService.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/service/CamelMavenVersionManager.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/service/CamelService.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/service/XmlUtils.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/util/IdeaUtils.java
- camel-idea-plugin/src/main/resources/META-INF/plugin.xml
- camel-idea-plugin/src/test/java/org/apache/camel/idea/service/XmlUtilsTest.java
- Remove fat package by grouping some classes in sub packages
- Moved two Util classes to the same package as the class which uses them and reduced the visiblity of these Utils classes
> Remove fat package and move two Utils classes to another location

- camel-idea-plugin/src/main/java/org/apache/camel/idea/documentation/CamelDocumentationProvider.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/documentation/CamelDocumentationProviderTestIT.java
- camel-idea-plugin/src/test/resources/testData/expected_doc.xml
unforatunately I wasn't able to test handleExternal, because IntelliJ's BrowserUtil.browse() method call opens a new browser tab every time the test is executed and mocking this method call didn't work out for me :/
> Add tests for documentation

- .travis.yml
- camel-idea-plugin/pom.xml
- camel-idea-plugin/src/main/java/org/apache/camel/idea/gutter/CamelRouteLineMarkerProvider.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/CamelLightCodeInsightFixtureTestCaseIT.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/gutter/GutterTestUtil.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/gutter/JavaCamelRouteLineMarkerProviderTestIT.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/gutter/MultiLanguageCamelRouteLineMarkerProviderTestIT.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/util/IdeaUtilsSkipEndpointValidationTestIT.java
- readme.md
This fix a few issues after upgrading IDEA SDK to 2017.3.2
- RelatedItemLineMarkerProvider has been a lot more restrict then previous. It now require to return smallest possible elements in the PSI tree for CamelRouteLineMarkerProvider
- Dispose test libraries add with PsiTestUtil.addLibrary
> Upgrade idea 2017 3 2

- camel-idea-plugin/src/main/java/org/apache/camel/idea/refereance/CamelBeanMethodReference.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/completion/JavaCamelBeanReferenceSmartCompletionTestIT.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/reference/JavaCamelBeanMethodReferenceTest.java
- camel-idea-plugin/src/test/resources/testData/CompleteJavaBeanMethodPropertyTestData.properties
- camel-idea-plugin/src/test/resources/testData/CompleteJavaBeanMultipleMethodTestData.java
- camel-idea-plugin/src/test/resources/testData/CompleteJavaBeanRoute3TestData.java
- camel-idea-plugin/src/test/resources/testData/CompleteJavaBeanRoute4TestData.java
- camel-idea-plugin/src/test/resources/testData/CompleteJavaBeanRoute5TestData.java
This solve the issue with method reference in Camel DSL is also
linked to any matching property names. So when jump to declaration
it would also present choices found in properties files
> Disable soft reference for bean methods reference.

- camel-idea-plugin/src/main/java/org/apache/camel/idea/refereance/CamelBeanMethodReference.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/refereance/CamelBeanReferenceContributor.java
- camel-idea-plugin/src/main/resources/META-INF/plugin.xml
- camel-idea-plugin/src/test/java/org/apache/camel/idea/completion/JavaCamelBeanReferenceSmartCompletionTestIT.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/reference/JavaCamelBeanMethodReferenceTest.java
- camel-idea-plugin/src/test/resources/testData/CompleteJavaBeanRoute7TestData.java
- camel-idea-plugin/src/test/resources/testData/CompleteJavaBeanTest2Data.java
- camel-idea-plugin/src/test/resources/testData/CompleteJavaBeanTestData.java
- camel-idea-plugin/src/test/resources/testData/RenameCamelBeanMethodRefResultTestData.java
- readme.md
This fix an issue with the CamelBeanMethodReference was used
incorrectly, and referer to the bean method and not the PsiLiteral bean DSL.
The result was when using "find usage" it just pointed to the
method itself and not the Camel Bean DSL
> Fix for find usage was not working from bean method to Camel bean DSL

- camel-idea-plugin/src/main/java/org/apache/camel/idea/annotator/CamelBeanMethodAnnotator.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/util/IdeaUtils.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/util/JavaMethodUtils.java
- camel-idea-plugin/src/main/resources/META-INF/plugin.xml
- camel-idea-plugin/src/test/java/org/apache/camel/idea/annotator/CamelBeanMethodAnnotatorTestIT.java
- camel-idea-plugin/src/test/resources/testData/annotator/method/AnnotatorJavaBeanRoute3TestData.java
- camel-idea-plugin/src/test/resources/testData/annotator/method/AnnotatorJavaBeanRoute4TestData.java
This is the first version of validation of ambiguous method calls
from camel bean DSL.
> Add validation for call ambiguous methods in bean calls

- camel-idea-plugin/src/main/java/org/apache/camel/idea/annotator/CamelBeanMethodAnnotator.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/refereance/CamelBeanMethodReference.java
- camel-idea-plugin/src/main/java/org/apache/camel/idea/util/JavaMethodUtils.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/annotator/CamelBeanMethodAnnotatorTestIT.java
- camel-idea-plugin/src/test/java/org/apache/camel/idea/reference/CamelBeanMethodReferenceTest.java
- camel-idea-plugin/src/test/resources/testData/annotator/method/AnnotatorJavaBeanRoute3TestData.java
- camel-idea-plugin/src/test/resources/testData/annotator/method/AnnotatorJavaBeanRoute5TestData.java
- camel-idea-plugin/src/test/resources/testData/completion/method/CompleteJavaBeanRoute8TestData.java
- camel-idea-plugin/src/test/resources/testData/completion/method/CompleteJavaBeanTest2Data.java
- camel-idea-plugin/src/test/resources/testData/completion/method/CompleteJavaBeanTest3Data.java
- This fix an issue with the reference logic preventing the user
for jumping to bean method when using parameters in the bean call.
The reference logic is limit to show all the matching method names regardless
it's a parameter references. Later we add more support to link it more
accurately to the method with parameters it should match.
- Fix an issue with ambiguous methods was mark, if the bean method call
was with parameters. Currently we are not able to accurately match the
bean method call. This will come later.
> Update the method reference to handle method calls with parameters

- camel-idea-plugin/src/main/resources/META-INF/plugin.xml
At some point between IDEA upgrades this has changed and the end point
completion in property files stop working. The reason why it's behave
like this can be find in the JavaClassReferenceCompletionContributor,
and the fact that it find a JavaClassReference for the specific
property result in it call the result.stopHere method
I post a question regarding this behaviour
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000181079-Strange-problem-with-our-customer-property-completion-contributor
> Fix an issue with code end point completion did not work in properties files

- install-intellij-libs.bat
the artifact installed in local .m2 has been renamed from resources_en
to properties-resources_en during work on #285 as another resources fo
ryaml has been introduced
Signed-off-by: Aurélien Pupier <apupier@redhat.com>
> Fix setup environment on Windows

- camel-idea-plugin/pom.xml
I think the old version (2018.1.6) was left in the 'ultimate' profile by mistake
> fix idea.version in ultimate profile (2018.1.6 -> 2018.3.4)

- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/CamelLightCodeInsightFixtureTestCaseIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/inspection/CamelInspectJavaJSonPathTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/inspection/CamelInspectJavaSimpleTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/inspection/CamelInspectXmlSimpleTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/inspection/CamelInspectionTestHelper.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/service/CamelCatalogServiceTestIT.java
It turns out after 2019.1 the InspectionTestCase has become "light",
so modifications to the test project like adding libraries etc.
are "sticking". You'll need to undo any (temporary) changes to your
project setp carefully in tearDown() or use dedicated LightProjectDescriptor instead.
https://intellij-support.jetbrains.com/hc/en-us/community/posts/360004337839-Inspection-TestCase-start-failing-after-upgrade
> Re-enable inspection test case.

- camel-idea-plugin/src/main/resources/META-INF/plugin.xml
For some reason this dependency was not needed in IDEA 2019.x
but in 2020.1 it is requirement
> Add missing dependency

- build.gradle
- camel-idea-plugin/build.gradle
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/catalog/CamelCatalogProvider.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/CamelCatalogService.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/CamelMavenVersionManager.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/CamelPreferenceService.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/CamelService.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/util/ArtifactCoordinates.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/CamelLightCodeInsightFixtureTestCaseIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/JavaCamelBeanReferenceSmartCompletionTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/JavaHeaderNameCompletionTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/JavaHeaderValueCompletionTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/PropertiesPropertyKeyCompletionSpringBootLegacyTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/PropertiesPropertyKeyCompletionSpringBootNoDownloadTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/PropertiesPropertyKeyCompletionSpringBootTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/reference/CamelBeanMethodReferenceTest.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/service/CamelCatalogServiceTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/service/CamelPreferenceServiceMock.java
- camel-idea-plugin/src/test/resources/META-INF/plugin.xml
- camel-idea-plugin/src/test/resources/log4j.properties
- camel-idea-plugin/src/test/resources/testData/completion/property/component-options.properties
- camel-idea-plugin/src/test/resources/testData/completion/property/data-format-options-with-old-name.properties
- camel-idea-plugin/src/test/resources/testData/completion/property/springboot-options.properties
fixes #700
If we use a specific version of Camel that is not the same as the one included in the plugin and the Camel Runtime is not the default one, then the metadata are not properly loaded consequently the name of components, languages, data formats cannot be retrieved when using Spring Boot as Camel Runtime.
* Add the ability to load also the runtime provider version
* Add a dynamic way to detect a runtime provider
* Add a dynamic way to find the catalog corresponding to a runtime provider
* Add the ability to support legacy runtime provider in case of Spring Boot
* Enable the cache of the catalog only when it is ready to use
* Clean up the class `CamelMavenVersionManager` by removing dead code, adding some log messages in case of errors and adding a utility method to avoid code …
> Ref #700 - Support specific catalog version for a Camel runtime provider

- camel-idea-plugin/build.gradle
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/annotator/BeanReferenceTypeAnnotator.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/CamelLightCodeInsightFixtureTestCaseIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/annotator/CamelSimpleAnnotatorTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/JavaCamelBeanReferenceSmartCompletionTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/JavaEndpointSmartCompletionTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/JavaEndpointSmartCompletionValueTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/JavaHeaderNameCompletionTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/JavaHeaderValueCompletionTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/PropertyEndpointSmartCompletionTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/documentation/CamelDocumentationProviderTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/documentation/CamelSmartCompletionDocumentationTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/inspection/CamelInspectJavaEndpointTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/inspection/CamelInspectJavaSimpleTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/inspection/CamelInspectXmlSimpleTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/inspection/CamelInspectionTestHelper.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/preference/annotator/CamelAnnotatorPageTest.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/preference/editorsettings/CamelEditorSettingsPageTest.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/reference/CamelBeanMethodReferenceTest.java
Fix commented/ignored tests after upgrade to Camel 3 & Intellij 2021.1
* Improve the way to define a `LightProjectDescriptor` to get rid of the directory `mockJDK`
* Re-add tests that are easy to fix
* Simplify asserts when possible
> Ref #590 - Re-add tests easy to fix

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/CamelPluginStartup.java
- camel-idea-plugin/src/main/resources/META-INF/plugin.xml
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/CamelProjectComponentTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/service/CamelServiceTestIT.java
fixes #606 
Late addition or removal of Apache Camel is not detected by the plugin such that we need to reopen the project to ensure that it is detected properly which is not really convenient for end users.
* Listen to roots changes for such purpose as suggested in [this thread](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206819849-How-to-listen-to-the-library-updates-on-Module-)
* Un-comment the unit tests `CamelProjectComponentTestIT` since they actually test module changes
* Migrate the unit tests `CamelProjectComponentTestIT` to make it work again with the target version of Intellij
The plugin can now detect Camel even if it is added later in an existing project and enable all its features consequently
> Ref #606 - Detect late addition or removal of Camel

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/completion/extension/CamelEndpointSmartCompletionExtension.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/preference/editorsettings/CamelEditorSettingsPage.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/CamelPreferenceService.java
- camel-idea-plugin/src/main/resources/META-INF/plugin.xml
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/JavaEndpointSmartCompletionTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/XmlEndpointSmartCompletionTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/YamlEndpointSmartCompletionTestIT.java
fixes #720 
For a better user experience, only the Kamelet options should be proposed by default.
* Add a new checkbox in the configuration of Camel to decide whether the Kamelet options should be suggested alone or not.
* Add a new boolean to store in the preferences of the project if the Kamelet options should be suggested alone or not.
* Ensure that only the required options are proposed in bold
* Adapt the code consequently
* Fixes warnings on modified classes (not related to the initial issue)
> Ref #720 - Allow to suggest only the Kamelet options

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebugProcess.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerEditorsProvider.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerIcons.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerRunner.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerSession.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelSuspendContext.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/ContextAwareDebugProcess.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/MessageReceivedListener.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/actions/CamelEvaluateAction.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/actions/CamelEvaluateActionHandler.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/actions/CamelSetValueAction.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/actions/CamelSetValueActionHandler.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/breakpoint/CamelBreakpoint.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/breakpoint/CamelBreakpointHandler.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/breakpoint/CamelBreakpointType.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/evaluator/CamelExpressionEvaluator.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/stack/CamelExecutionStack.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/stack/CamelMessageInfo.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/stack/CamelStackFrame.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/stack/MapOfObjectFieldDefinitionValue.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/stack/ObjectFieldDefinitionValue.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/ui/CamelDebuggerEvaluationDialog.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/ui/CamelExpressionInputComponent.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/ui/CamelExpressionParameters.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/ui/CamelSetValueDialog.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/ui/CamelSetValueTargetPanel.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/util/ClasspathUtils.java
While investigating in how the recent improvements in the Debugger of Apache Camel can be leveraged in the IntelliJ plugin, I realized that many classes in the package `debugger` has warnings raised by IntelliJ. Moreover there are many line of codes that are commented which make the code very hard to read. To improve the maintainability of this package, it could be nice to address the warnings raised by IntelliJ.
* Use the logger instead of calling `e.printStackTrace()`
* Use `final` keyword on fields that are not modified which prevents visibility issues
* Use lambda when possible to improve the readability of the code
* Avoid setting the size to the array when copying a collection into an array
* Remove commented code
* Replace deprecated code when possible
* Inline the code instead of …
> Fix warnings in the debugger package

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerPatcher.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/ui/CamelRunnerConfPanel.form
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/ui/CamelRunnerConfPanel.java
- camel-idea-plugin/src/main/resources/META-INF/plugin.xml
fixes #729 
For now, the Camel runner has only fixed parameters which could be an issue, especially with the Quarkus runtime as the Camel runner is the only way to launch the application with the Camel Debugger automatically added and set up.
* Adds a new text field in the UI to provide additional plugin parameters 
* Registers the additional plugin parameters  as `MavenRunnerParameters`'s goals
* Injects the maven goals `clean`, `compile` and the plugin goal as first program parameters
> Ref #729 - Support custom plugin parameters in the Camel Runners

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebugProcess.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerRunner.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerSession.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/MessageReceivedListener.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/stack/CamelMessageInfo.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/stack/CamelStackFrame.java
- camel-idea-plugin/src/main/resources/META-INF/plugin.xml
fixes #732 
If we set several breakpoints or we set one breakpoint and we invoke `step over` command, in case we have a route with regular incoming messages, the debugger keeps on switching from different active breakpoints which makes the debugging hardly understandable.
* Processes the suspended breakpoint node ids as batch
* Keeps only one Camel message per batch and ideally the one corresponding to the latest message processed
* Prevents getting `IndexNotReadyException` when collecting message info
* Sorts the messages by timestamp to get a more predictable behavior
* Adds the exchange Id as variables accessible from the debugger view
The debugger doesn't switch anymore from one breakpoint to another.
> Ref #732 - Improve the multi-breakpoints support of the Camel Debugger

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerPatcher.java
fixes #749 
If the debugger is disabled, it is still added automatically which is not expected.
* Add the missing test to skip the addition of the debugger when it is disabled
> Ref #749: Don't add Camel debugger when disabled

- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/gutter/JavaCamelRouteLineMarkerProviderTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/gutter/MultiLanguageCamelRouteLineMarkerProviderTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/gutter/XmlCamelRouteLineMarkerProviderTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/gutter/YamlCamelRouteLineMarkerProviderTestIT.java
Related to #590
Some tests are commented because they don't pass since the migration to Camel 3 & Intellij 2021.1.
* Re-add the tests
* Adapt the tests to make them pass
* Fix some violations
> Ref #590: Re-add the gutter tests

- .github/workflows/ci-build.yaml
- build-all.sh
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/completion/header/CamelYamlHeaderValueCompletion.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/completion/property/CamelYamlPropertyKeyCompletion.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/CamelLightCodeInsightFixtureTestCaseIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/PropertiesPropertyKeyCompletionSpringBootLegacyTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/YamlPropertyKeyCompletionTestIT.java
fixes #754 
Some tests are failing on Windows OS.
* Add windows as OS to be tested by the CI
* Use `\n` as line separator since IntelliJ [manages it automatically](https://intellij-support.jetbrains.com/hc/en-us/community/posts/206125949/comments/206718299)
* Fix the way to retrieve `gradle.properties` to make it OS independent
* Add more flexibility to the hack that removes the jaxb libs to avoid failures
* Skip the tests that fail when the jaxb libs are not removed properly
> Ref #754: Make the tests pass on Windows OS

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerPatcher.java
fixes #760 
When launching the debugger on Windows OS, we get an error `java.nio.file.InvalidPathException: Illegal char <:> at index 2`.
* Use an OS-independent way to add dependencies to the classpath
> Ref #760: Use an OS-independent way to add dependencies to the classpath

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/extension/CamelIdeaUtilsExtension.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/gutter/CamelRouteLineMarkerProvider.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/extension/camel/JavaCamelIdeaUtils.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/extension/camel/XmlCamelIdeaUtils.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/extension/camel/YamlCamelIdeaUtils.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/util/CamelIdeaUtils.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/gutter/JavaCamelRouteLineMarkerProviderTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/gutter/MultiLanguageCamelRouteLineMarkerProviderTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/gutter/XmlCamelRouteLineMarkerProviderTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/gutter/YamlCamelRouteLineMarkerProviderTestIT.java
- camel-idea-plugin/src/test/resources/testData/JavaCamelRouteLineMarkerProviderTestData.java
- camel-idea-plugin/src/test/resources/testData/XmlCamelRouteLineMarkerProviderTestData.xml
- camel-idea-plugin/src/test/resources/testData/YamlCamelRouteLineMarkerProviderTestData.yaml
fixes #413 
When using the rest DSL, no gutter is shown for `rest()`
* Move the logic that identifies patterns for gutter in extensions
* Add test with a rest definition without URI for each supported extension
* Fix violations on files modified (not related to the initial issue)
> Ref #413: Show Camel gutter for rest()

- camel-idea-plugin/build.gradle
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerSession.java
- camel-idea-plugin/src/main/resources/META-INF/plugin.xml
fixes #755 
Starting from 3.19, the source location received for java classes only contains the name of the file instead of the FQN, the code needs to be adapted consequently.
* Use several locations for Java classes to support Camel versions before and after 3.19
* Fix violations
* Add the arguments as comments to launch `runIde` with the remote debugger and/or increase the verbosity of Grape (not related to the original issue)
> Ref #755: Adapt the debugger to Camel 3.19+

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/annotator/CamelEndpointAnnotator.java
- camel-idea-plugin/src/main/resources/META-INF/plugin.xml
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/annotator/CamelEndpointAnnotatorTestIT.java
fixes #426 
We would like to be able to strike through deprecated options in URI.
* Add support for deprecated options in the `EndpointValidationResult`
* Set specific text attributes in case of deprecation to have it strikeout
* Fix violations
* Re-add commented tests
* Add support for duration options in the `EndpointValidationResult`
> Ref #426: Strike through deprecated options in URI

- camel-idea-plugin/build.gradle
- camel-idea-plugin/grapeConfig.xml
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/catalog/CamelCatalogProvider.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/CamelService.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/util/ArtifactCoordinates.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/PropertiesPropertyKeyCompletionSpringBootLegacyTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/service/CamelCatalogProviderWithKarafArtifactTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/service/CamelCatalogProviderWithQuarkusArtifactTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/service/CamelCatalogProviderWithSpringBootArtifactTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/service/CamelCatalogProviderWithoutRuntimeArtifactTestIT.java
fixes #769 
When we force a runtime by settings if the corresponding core artifacts are not part of the dependencies of the project, the catalog is not downloaded while we would expect to download it anyway.
* Add a fallback method that will retrieve the catalog corresponding to the version of Camel
* Do nothing in the case of Quarkus as the versions are different
* Add a specific `grapeConfig.xml` as a temporary workaround to prevent dependency retrieval issue
> Ref #769: Allow to load a runtime provider w/o the core artifacts

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/documentation/CamelDocumentationProvider.java
fixes #773
Browsing endpoint options quick docs causes error of type `cannot be presented [Plugin: org.apache.camel]`
* Provide the content of the doc to present also with the `getText` method
> Ref #773: Prevent doc generation issue by providing it from getText

- build-all.sh
- gradle.properties
A new maintenance version of IDEA 2022.2 has been released and needs to be supported.
* Bump the default version of IDEA used to `2022.2.4`
* Bump the version of IDEA 2022.2 tested by the CI to `2022.2.4`
> Bump IDEA to 2022.2.4

- build-all.sh
The build always fails due to a clean issue on Windows.
* Call the clean task separately
* Update the versions of IntelliJ against which the tests are launched
> Fix the build on Windows

- camel-idea-plugin/build.gradle
- gradle.properties
New versions of IntelliJ have been released, the supported versions should be shifted accordingly.
* Change the default IntelliJ version used to the latest version
* Adapt the configuration of the IntelliJ gradle plugin to the supported versions
> Update the IntelliJ versions

- build.gradle
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/annotator/AbstractCamelAnnotator.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/annotator/CamelBeanMethodAnnotator.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/annotator/CamelEndpointAnnotator.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/completion/extension/PropertiesPropertyPlaceholdersSmartCompletion.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/completion/extension/YamlPropertyPlaceholdersSmartCompletion.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/inspection/AbstractCamelInspection.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/intention/CamelAddEndpointIntention.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/extension/camel/XmlCamelIdeaUtils.java
- config/checkstyle/checkstyle.xml
fixes #837 
All the IDEA versions supported by the plugin need Java 17, so we can start using the Java 17 syntax in the code however, for now, it is not yet possible because it is rejected by the current version of checkstyle used in the plugin. 
* Upgrades the version of checkstyle to the latest version
* Updates the file `checkstyle.xml` to be compatible with this new version of checkstyle
* Fixes the violations raised by the plugin
It is now possible to use the Java 17 syntax in the code of the plugin
> Ref #837: Bump the checkstyle's version to use Java 17 syntax

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerPatcher.java
- camel-idea-plugin/src/main/resources/META-INF/plugin.xml
fixes #641 (part 2)
The first part of the fix for #641 doesn't cover well the multi-project build as it assumes that the name of the project matches the name of a direct subdirectory which is not always true.
* Generates Kotlin/Groovy code in the build file that adds the dependencies from the root build file
* Generates Kotlin/Groovy code in the settings file to refer to the location of the generated build file
The multi-project builds can now benefit from the Camel Debugger
> Ref #641: Camel Debugger - Improve multi-project build support

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/completion/extension/CamelEndpointSmartCompletionExtension.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/completion/property/CamelYamlPropertyKeyCompletion.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/preference/editorsettings/CamelEditorSettingsPage.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerPatcher.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerRunner.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelExternalSystemTaskDebugRunner.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/CamelCatalogService.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/CamelPreferenceService.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/CamelProjectPreferenceService.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/CamelService.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/JavaEndpointSmartCompletionTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/PropertiesPropertyKeyCompletionTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/PropertyValueCompletionTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/XmlEndpointSmartCompletionTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/YamlEndpointSmartCompletionTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/YamlPropertyKeyCompletionTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/service/CamelCatalogServiceTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/service/CamelPreferenceServiceTestIT.java
fixes #844 
Up to now, all the preferences are global while some preferences should be scoped to the project so we need to review them and adapt their scope if needed.
* Moves "EnableCamelDebugger", "CamelDebuggerAutoSetup", "OnlyShowKameletOptions" and "CamelCatalogProvider" to the project settings
> Ref #844: Move appropriate settings to project settings

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/completion/extension/YamlPropertyPlaceholdersSmartCompletion.java
After upgrading `kubernetes-model-apiextensions` from `6.6.2` to `6.7.0`, a test fails with an error of type `java.lang.NoSuchMethodError at YamlPropertyPlaceholdersSmartCompletion.java:50`
* Uses the new correct constructor.
> Avoid NoSuchMethodError when creating a SafeConstructor

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/documentation/CamelDocumentationProvider.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/CamelService.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/CamelProjectComponentTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/PropertiesPropertyKeyCompletionSpringBootLegacyTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/inspection/CamelInspectionTestHelper.java
fixes #848 
fixes #648
Camel 4 is about to be released but the plugin doesn't support it yet. Moreover, Camel 2 is a bit old now, so the support of it needs to be dropped.
* Makes the test checking for core maven dependency more flexible to cover Camel 3 and 4
* Removes all references to Camel 2
> Ref #848: Add support of Camel 4 and drop Camel 2

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/util/ArtifactCoordinates.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/CamelProjectComponentTestIT.java
fixes #862
When we try to open a project that uses a milestone version of Camel, we end up with a warning indicating that the catalog could not be loaded automatically
* Avoid altering the case of the version since a maven repository is case-sensitive
> Ref #862: Keep the case of the version

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/extension/camel/JavaCamelIdeaUtils.java
- camel-idea-plugin/src/main/resources/META-INF/plugin.xml
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/formatter/CamelPostFormatProcessorIT.java
- camel-idea-plugin/src/test/resources/testData/formatter/after/EntireFile.txt
- camel-idea-plugin/src/test/resources/testData/formatter/after/MalformedRoute.txt
- camel-idea-plugin/src/test/resources/testData/formatter/after/PartialFormatWithRoute.txt
- camel-idea-plugin/src/test/resources/testData/formatter/after/RouteWithDataFormatDSL.txt
- camel-idea-plugin/src/test/resources/testData/formatter/after/RouteWithExpressions.txt
- camel-idea-plugin/src/test/resources/testData/formatter/before/MalformedRoute.java
- camel-idea-plugin/src/test/resources/testData/formatter/before/RouteWithDataFormatDSL.java
- camel-idea-plugin/src/test/resources/testData/formatter/before/RouteWithExpressions.java
fixes #864 
The expression clauses are formatted but we would rather prefer not to format them for clarity.
* Excludes the methods of `ExpressionClause` from the methods to format
* Adds support of DataFormat DSL and Language DSL
* Prevents the Java DSL Formatter from failing when the route is not properly written
* Reformat the affected class
Here is an example of formatted code
```
from("timer:foo")
.setBody(simple("xxx"))
.setBody().simple("xxx", String.class)
.setBody().constant("xxx");
from("disruptor:foo")
.transform(constant("Bye World"))
.to("mock:result");
from("direct:a")
.split(
expression()
.tokenize()
.token("\n")
.end())
.to("mock:a");
from("direct:b")
.setBody().expression(
expression()
.simple()
.expression("Hello World Out")
.end())
.to("mock:b");
from("direct:c") …
```
> Ref #864: Java DSL Formatter - Avoid formatting expression clauses

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerPatcher.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerSession.java
fixes #871 
The Camel Debugger is no more working when using Camel V4, indeed it never stops at the breakpoints.
* Calls `suspendedBreakpointNodeIds` instead of `getSuspendedBreakpointNodeIds` since it has been removed in Camel 4 and it exists since Camel 3.15 which is the first version for which the Camel Debugger is supported
* Fixes a potential NPE
> Ref #871: Adapt the debugger code to Camel 4

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/ui/CamelRunnerConfPanel.form
- camel-idea-plugin/src/main/resources/messages/LegacyMavenConfigurableBundle.properties
fixes #904 
With IntelliJ IDEA 2023.2.2 (Community Edition), when we try to access the Camel debug configurations, we end up with a  `MissingResourceException` due to the removal of a key on which we rely from the resource bundle of the maven plugin [by this commit](https://github.com/JetBrains/intellij-community/commit/6c08a2f231186126f650cd0c5df434e1698879e7).
* Copy all the maven resource bundle keys used by the plugin to an internal resource bundle to fix the issue and prevent the same issue on other keys in the future
> Ref #904: Keep a copy of maven resource bundle keys

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/extension/camel/JavaCamelIdeaUtils.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/formatter/CamelPostFormatProcessorIT.java
- camel-idea-plugin/src/test/resources/testData/formatter/after/Formatting879.txt
- camel-idea-plugin/src/test/resources/testData/formatter/after/RouteWithExpressions.txt
- camel-idea-plugin/src/test/resources/testData/formatter/before/Formatting879.java
- camel-idea-plugin/src/test/resources/testData/formatter/before/RouteWithExpressions.java
fixes #879 
When we try to format a Camel route in a project where Camel routes are defined in different files, we can end up with exceptions of type `IndexOutOfBoundsException`.
* Ensure that the Camel routes to format are only those that are in the target file
* Ensure that the Camel routes to format are sorted by offset
* Improve the way to format the predicates that could be inlined or not
* Improve the way to format the predicates that could be inside a when clause or not
> Ref #879: Filter and order the routes to format

- camel-idea-plugin/build.gradle
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerSession.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/CamelMavenVersionManager.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/annotator/CamelEndpointAnnotatorTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/JavaEndpointSmartCompletionValueTestIT.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/JavaHeaderValueCompletionTestIT.java
- camel-idea-plugin/src/test/resources/testData/completion/header/set/HeaderValueDefaultSuggestion.java
- camel-idea-plugin/src/test/resources/testData/completion/header/set/HeaderValueDefaultSuggestion.xml
- camel-idea-plugin/src/test/resources/testData/completion/header/set/HeaderValueDefaultSuggestion.yaml
- camel-idea-plugin/src/test/resources/testData/completion/header/set/HeaderValueDefaultSuggestionResult.java
- camel-idea-plugin/src/test/resources/testData/completion/header/set/HeaderValueDefaultSuggestionResult.xml
- camel-idea-plugin/src/test/resources/testData/completion/header/set/HeaderValueDefaultSuggestionResult.yaml
- camel-idea-plugin/src/test/resources/testData/completion/header/set/HeaderValueEnumSuggestionsUnknownComponent.java
- camel-idea-plugin/src/test/resources/testData/completion/header/set/HeaderValueEnumSuggestionsUnknownComponent.xml
- camel-idea-plugin/src/test/resources/testData/completion/header/set/HeaderValueEnumSuggestionsUnknownComponent.yaml
- camel-idea-plugin/src/test/resources/testData/completion/header/set/HeaderValueEnumSuggestionsUnknownComponentResult.java
- camel-idea-plugin/src/test/resources/testData/completion/header/set/HeaderValueEnumSuggestionsUnknownComponentResult.xml
- camel-idea-plugin/src/test/resources/testData/completion/header/set/HeaderValueEnumSuggestionsUnknownComponentResult.yaml
- camel-idea-plugin/src/test/resources/testData/completion/header/set/HeaderValueEnumSuggestionsWithFullyQualifiedConstantAsName.java
- camel-idea-plugin/src/test/resources/testData/completion/header/set/HeaderValueEnumSuggestionsWithFullyQualifiedConstantAsNameResult.java
- gradle.properties
fixes #898 
Camel 4.0 has been released so we would like to upgrade Camel to that version.
* Use a specific version for the Karaf catalog as there is no version 4 available
* Add Groovy/Ivy as runtime dependencies explicitly since they are needed by the plugin since they are no longer transitively inherited by Camel
* Adapt the code to Camel 4
* Adapt some tests to the Camel 4 catalog
* Remove the test ensuring the deprecating warning could be detected by the plugin because there are no more deprecated options in the Camel 4 catalog
* Upgrade all camel dependencies to the latest versions
> Ref #898: Upgrade to Camel 4.0

- camel-idea-plugin/build.gradle
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerPatcher.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/CamelMavenVersionManager.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/MavenArtifactRetrieverContext.java
fixes #751 
Instead of using Groovy Grape to download the artifacts, for the sake of uniformity, we would like to reuse the code of Camel based on the Apache Maven APIs.
* Remove all dependencies related to Groovy Grape
* Remove all system properties related to Groovy Grape
* Replace Groovy Grave with the new class `MavenArtifactRetrieverContext` based on `MavenDownloader` from Camel
> Ref #751: Use Apache Maven APIs for downloading artifacts

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/CamelJBangRunProfileState.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerPatcher.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerSession.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/CamelRuntime.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/util/ArtifactCoordinates.java
fixes #908 
Several problems prevent the Camel Debugger from working properly with Camel SpringBoot 4 applications. 
If the debugger is launched using a Java run configuration, then the Camel Debugger will be able to connect to the Camel SpringBoot application using JMX, but an error indicating that `camel-spring-xml` must added to the classpath is thrown. 
If the debugger is launched using the Camel run configuration for SpringBoot, then the Camel Debugger won't be able to connect as the Camel SpringBoot application is launched in a different process. 
* Allow to add an additional artifact when configuring the debugger to also add `camel-spring-xml` for SpringBoot
* Access to JMX using a JMX service URL in case of SpringBoot
* Avoid Gradle issues when the generated parameters have not …
> Ref #908: Camel Debugger - Add support of Camel SpringBoot 4

- camel-idea-plugin/build.gradle
- gradle.properties
Dependabot sees `maven-resolver-api` and `maven-resolver-impl` as two different libraries while they should be seen and upgraded as single one.
* Use a property to define globally the version of the maven resolver used
> chore: externalize the version of the maven resolver

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/ui/CamelJBangRunnerConfPanel.java
fixes #926 
The file selector of the Camel JBang Application Run Configuration doesn't filter out idea files, it should be improved to avoid selecting random files and to ease the selection of a file when there is only one file in the project
* Only allow to select files with allowed extensions
* Auto-select the first allowed file
* Replace the old file chooser to support multi-selection
> Ref #926: Allow to select only camel-jbang supported files

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerPatcher.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerSession.java
- camel-idea-plugin/src/main/resources/META-INF/plugin.xml
fixes #930 
When using the Camel Quarkus, the Camel Debugger doesn't work because he cannot retrieve the source file corresponding to the breakpoints known by Camel.
* Add the file name as a potential location known by Camel
* Avoid calling `compile` in the case of Quarkus as it could prevent the automatic addition of the Camel Debugger from working properly
* Set the environment variable `CAMEL_MAIN_DEBUGGING` required by Camel Quarkus to enable the camel-debug extension
> Ref #930: camel-debugger - Allow to find the source file by file name

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/inspection/AbstractCamelInspection.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/ui/CamelDebuggerEvaluationDialog.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/extension/camel/JavaCamelIdeaUtils.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/util/CamelIdeaUtils.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/util/IdeaUtils.java
- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/util/JavaClassUtils.java
- camel-idea-plugin/src/main/resources/META-INF/plugin.xml
* Add `EndpointRouteBuilder` to the list of classes detected
* Add Javax and JakartaEE inject bean annotations to the detection of injected beans
> Fix named beans detection and route builder class hierarchy.

- camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/extension/camel/JavaCamelIdeaUtils.java
- camel-idea-plugin/src/test/java/com/github/cameltooling/idea/formatter/CamelPostFormatProcessorIT.java
- camel-idea-plugin/src/test/resources/testData/formatter/after/Formatting945.txt
- camel-idea-plugin/src/test/resources/testData/formatter/before/Formatting945.java
fixes #945 
When using the keyword new in the middle of Camel route, the formatting doesn't work as expected so it needs to be improved.
* Ensure that new expressions are not seen as method calls
> Ref #945: formatting - Exclude new expressions

- camel-idea-plugin/build.gradle
No need to keep a dependency that is no longer used and is updated regularly for nothing by dependabot.
* Remove spring-context from the test dependencies
> Remove spring-context from the test dependencies

- src/main/java/com/github/cameltooling/idea/Constants.java
- src/main/java/com/github/cameltooling/idea/completion/extension/CamelPropertyCompletion.java
- src/main/java/com/github/cameltooling/idea/completion/extension/CamelPropertyPlaceholderSmartCompletionExtension.java
- src/main/java/com/github/cameltooling/idea/completion/extension/PropertiesPropertyPlaceholdersSmartCompletion.java
- src/main/java/com/github/cameltooling/idea/completion/extension/YamlPropertyPlaceholdersSmartCompletion.java
- src/main/java/com/github/cameltooling/idea/reference/AbstractPropertyPlaceholderReferenceContributor.java
- src/main/java/com/github/cameltooling/idea/reference/CamelPropertyPlaceholderReferenceContributor.java
- src/main/java/com/github/cameltooling/idea/reference/blueprint/BlueprintPropertyPlaceholderReferenceContributor.java
- src/main/java/com/github/cameltooling/idea/util/BeanUtils.java
- src/main/java/com/github/cameltooling/idea/util/BlueprintUtils.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/com/github/cameltooling/idea/completion/extension/BlueprintPropertyPlaceholderCompletionTestIT.java
- src/test/resources/testData/completion/propertyplaceholder/xml/blueprint.xml
- src/test/resources/testData/completion/propertyplaceholder/xml/blueprint_after.xml
- src/test/resources/testData/completion/propertyplaceholder/xml/blueprint_with_camel.xml
- src/test/resources/testData/completion/propertyplaceholder/xml/blueprint_with_cxf.properties
- src/test/resources/testData/completion/propertyplaceholder/xml/blueprint_with_cxf.xml
- src/test/resources/testData/completion/propertyplaceholder/xml/blueprint_with_cxf_after.xml
property placeholders instyle of `${...}`, in blueprint xml files
> support blueprint property placeholders

- src/main/java/com/github/cameltooling/idea/reference/endpoint/parameter/CamelEndpointParameterReferenceContributor.java
- src/main/java/com/github/cameltooling/idea/reference/endpoint/parameter/EndpointParameterReference.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/com/github/cameltooling/idea/CamelLightCodeInsightFixtureTestCaseIT.java
- src/test/java/com/github/cameltooling/idea/reference/endpoint/parameter/CamelEndpointParametereferenceContributorTest.java
like so:
pointing to `org.apache.camel.component.file.GenericFileEndpoint#setAppendChars`
I'm not quite sure how to determine which class the query parameter is actually located in, and whether I can determine this programmatically, so I went with the most primitive approach - take the component class name (e.g. DirectComponent), replace Component with Endpoint, or Configuration, and try to find appropriate setter there. If there's a better way, or if there's more possible places to look in, I'll gladly change the logic.
> add references from endpoint uri parameters to their corresponding setters in camel classes (*Endpoint, *Configuration)

- src/main/java/com/github/cameltooling/idea/annotator/CamelJSonPathAnnotator.java
- src/main/java/com/github/cameltooling/idea/annotator/CamelLanguageAnnotator.java
- src/main/java/com/github/cameltooling/idea/preference/annotator/CamelAnnotatorPage.java
- src/main/java/com/github/cameltooling/idea/service/CamelPreferenceService.java
- src/main/java/com/github/cameltooling/idea/service/CamelService.java
- src/main/java/com/github/cameltooling/idea/service/extension/camel/JavaCamelIdeaUtils.java
- src/main/resources/META-INF/plugin.xml
- src/test/java/com/github/cameltooling/idea/annotator/CamelJQAnnotatorTestIT.java
- src/test/java/com/github/cameltooling/idea/preference/annotator/CamelAnnotatorPageTest.java
This will require Camel 4.14.1 so lets wait until we have this release
> Add support for validating JQ
