.travis.yml
buildingtools/camel-checkstyle-suppressions.xml
install-intellij-libs.sh
pom.xml
readme.md
src/main/java/org/apache/camel/idea/completion/extension/YamlPropertyPlaceholdersSmartCompletion.java
src/test/java/org/apache/camel/idea/completion/extension/YamlPropertyPlaceholdersSmartCompletionTestIT.java
src/test/resources/testData/CompleteYmlPropertyTestData.java
src/test/resources/testData/CompleteYmlPropertyTestData.yml

This one was a tough one to crack but we now have IntelliJ plugin testing working both from IDEA and Maven.
Additional test cases will be added in another pull-request

Intellij plugin test

---

pom.xml
readme.md

- For running the with ultimate version enable the maven profile "ultimate"

#68 Fixing an issue with running unit test with Ultimate version of IDEA

---

camel-idea-plugin/src/main/java/org/apache/camel/idea/documentation/CamelDocumentationProvider.java

This enables the quick documentation popup for the selected route option in the completion popup.

Allow quick documentation for route option

---

camel-idea-plugin/src/main/java/org/apache/camel/idea/documentation/CamelDocumentationProvider.java

#161 Added the option name in the quick documentation popup

---

.travis.yml
install-intellij-libs.sh

- Enable Travis CI Cache feature
- Test if Intellij artifacts is already installed.

Enable Travis CI Cache feature

---

camel-idea-plugin/src/main/java/org/apache/camel/idea/inspection/CamelGroovyInspection.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/inspection/CamelJavaInspection.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/inspection/CamelKotlinInspection.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/inspection/CamelScalaInspection.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/inspection/CamelXmlInspection.java
install-intellij-libs.sh

The Javadoc for getShortName specific says you should not overwrite this method
and the result is an ERROR is throw

Fix shortname override

---

camel-idea-plugin/src/main/java/org/apache/camel/idea/documentation/CamelDocumentationProvider.java

#228 Fixed quick doc title

---

camel-idea-plugin/src/main/java/org/apache/camel/idea/gutter/CamelRouteLineMarkerProvider.java

#108 The gutter icon is not clickable

---

camel-idea-plugin/src/test/java/org/apache/camel/idea/gutter/GutterTestUtil.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/gutter/JavaCamelRouteLineMarkerProviderTestIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/gutter/MultiLanguageCamelRouteLineMarkerProviderTestIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/gutter/XmlCamelRouteLineMarkerProviderTestIT.java

Fixed the failing unit test introduced in PR #274

Fix failing unit test

---

camel-idea-plugin/src/main/java/org/apache/camel/idea/util/CamelIdeaUtils.java

fixed #277: Scala routes using "==>" have no gutter icon

---

.travis.yml
camel-idea-plugin/pom.xml
camel-idea-plugin/src/main/java/org/apache/camel/idea/CamelProjectComponent.java
camel-idea-plugin/src/main/resources/META-INF/plugin.xml
readme.md

This also include this fix for #310

Upgrade IDEA 2017.2

---

readme.md

simplify readme so there is less to do when someone new wants to work with the code

simplify readme

---

camel-idea-plugin/src/main/java/org/apache/camel/idea/service/CamelService.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/service/XmlErrorHandler.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/service/XmlUtils.java

add ErrorHandler for XML validation to avoid default error messages in the console

add custom errorhandler for XML valdation

---

camel-idea-plugin/src/main/java/org/apache/camel/idea/annotator/CamelEndpointAnnotator.java

Fixing typo

---

camel-idea-plugin/pom.xml
install-intellij-libs.bat
install-intellij-libs.sh

group id and directory when installing into the new local m2 folder

Fix a problem with dependencies was not pointing to correct

---

camel-idea-plugin/src/main/java/org/apache/camel/idea/util/StringUtils.java

Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

corrected the hasQuestionMark check in stringutils

---

camel-idea-plugin/src/main/java/org/apache/camel/idea/service/extension/camel/JavaCamelIdeaUtils.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/completion/JavaCamelBeanReferenceSmartCompletionTestIT.java

Handle method as bean . Not sure if this is the right way, but it seems to work in my Idea.

Bean method completion in "when().method(<cursor>) #386"

---

camel-idea-plugin/pom.xml
camel-idea-plugin/src/main/java/org/apache/camel/idea/annotator/CamelJSonPathAnnotator.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/extension/CamelIdeaUtilsExtension.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/inspection/AbstractCamelInspection.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/inspection/CamelInspection.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/preference/CamelPreferenceEntryPage.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/preference/editorsettings/CamelEditorSettingsPage.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/preference/properties/CamelEditDialog.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/service/CamelPreferenceService.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/service/CamelService.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/service/extension/camel/CamelIdeaUtils.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/service/extension/camel/JavaCamelIdeaUtils.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/service/extension/camel/XmlCamelIdeaUtils.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/util/CamelIdeaUtils.java
camel-idea-plugin/src/main/resources/META-INF/plugin.xml
camel-idea-plugin/src/test/java/org/apache/camel/idea/CamelLightCodeInsightFixtureTestCaseIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/CamelProjectComponentTestIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/annotator/CamelJSonPathAnnotatorTestIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/inspection/CamelInspectJavaJSonPathTestIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/inspection/CamelInspectJavaSimpleTestIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/inspection/CamelInspectXmlSimpleTestIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/preference/editorsettings/CamelEditorSettingsPageTest.java
camel-idea-plugin/src/test/resources/testData/barroute/expected.xml
camel-idea-plugin/src/test/resources/testData/barroute/src/BarRoute.java

Just a bit dirty prototype on this - needs a bit more polish. Also the unit tests with extra JARs on the classpath is a bit ugly with how to grab those mvn artifacts and turn them into idea libraries.

Add real time jsonpath validation.

---

camel-idea-plugin/src/main/java/org/apache/camel/idea/util/CamelIdeaUtils.java

This error is reported by a user, but I have not been able to
reproduce it my self or in a unit test

Fix an issue with the getQualifiedName can return null

---

camel-idea-plugin/pom.xml

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

Support space in path for test launching

---

.travis.yml
camel-idea-plugin/pom.xml
camel-idea-plugin/src/main/resources/META-INF/plugin.xml
camel-idea-plugin/src/test/java/org/apache/camel/idea/CamelLightCodeInsightFixtureTestCaseIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/documentation/CamelDocumentationProviderTestIT.java
camel-idea-plugin/src/test/resources/testData/documentation/javaClassQuickNavigateInfo.html

- Introduce new dependencies
- Add property for running headless, otherwise it fails because it can't
link to touch bar c library

Upgrade IDEA to 2018.3.4

---

camel-idea-plugin/src/main/java/org/apache/camel/idea/annotator/CamelEndpointAnnotator.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/contributor/CamelJavaReferenceContributor.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/contributor/CamelXmlReferenceContributor.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/extension/CamelEndpointNameCompletionExtension.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/extension/CamelEndpointSmartCompletionExtension.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/extension/CamelIdeaUtilsExtension.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/gutter/CamelRouteLineMarkerProvider.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/reference/CamelBeanMethodReference.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/reference/CamelBeanReferenceContributor.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/reference/CamelPsiReferenceProvider.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/reference/endpoint/CamelEndpoint.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/reference/endpoint/CamelEndpointPsiReferenceProvider.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/reference/endpoint/direct/DirectEndpointPsiElement.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/reference/endpoint/direct/DirectEndpointReference.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/reference/endpoint/direct/DirectEndpointReferenceContributor.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/reference/endpoint/direct/DirectEndpointStartSelfReference.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/service/CamelPreferenceService.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/service/extension/camel/JavaCamelIdeaUtils.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/service/extension/camel/XmlCamelIdeaUtils.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/util/CamelIdeaUtils.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/util/IdeaUtils.java
camel-idea-plugin/src/main/resources/META-INF/plugin.xml
camel-idea-plugin/src/test/java/org/apache/camel/idea/completion/extension/CamelEndpointNameCompletionExtensionIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/gutter/XmlCamelRouteLineMarkerProviderTestIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/reference/CamelDirectEndpointReferenceTest.java
camel-idea-plugin/src/test/resources/testData/completion/endpointname/CompleteDirectEndpointNameTestData.java
camel-idea-plugin/src/test/resources/testData/completion/endpointname/CompleteDirectEndpointNameTestData.xml

I've enhanced support for 'direct' endpoints - mainly code completion and references.

direct endpoint enhancements (code completion, references)

---

.travis.yml
camel-idea-plugin/pom.xml
camel-idea-plugin/src/main/resources/META-INF/plugin.xml
camel-idea-plugin/src/test/java/org/apache/camel/idea/CamelLightCodeInsightFixtureTestCaseIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/documentation/CamelDocumentationProviderTestIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/inspection/CamelInspectJavaEndpointTestIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/inspection/CamelInspectJavaJSonPathTestIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/inspection/CamelInspectJavaSimpleTestIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/inspection/CamelInspectXmlEndpointTestIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/inspection/CamelInspectXmlSimpleTestIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/reference/CamelBeanMethodReferenceTest.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/service/CamelCatalogServiceTestIT.java
pom.xml

This upgrade to IDEA 2019.1
I had to disable to a few test cases because it behave strange after upgrade. A issue has been create to find a solution to them.

Upgrade idea 2019 1

---

camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/extension/CamelEndpointNameCompletionExtension.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/extension/CamelIdeaUtilsExtension.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/reference/endpoint/CamelEndpointPsiReferenceProvider.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/service/extension/camel/JavaCamelIdeaUtils.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/service/extension/camel/XmlCamelIdeaUtils.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/util/CamelIdeaUtils.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/completion/extension/CamelEndpointNameCompletionExtensionIT.java
camel-idea-plugin/src/test/resources/testData/completion/endpointname/CompleteDirectEndpointNameAtInvalidPlace.java
camel-idea-plugin/src/test/resources/testData/completion/endpointname/CompleteDirectEndpointNameAtInvalidPlace.xml
camel-idea-plugin/src/test/resources/testData/completion/endpointname/CompleteDirectEndpointNameInNonUriAttribute.xml
camel-idea-plugin/src/test/resources/testData/completion/endpointname/CompleteDirectEndpointNameInRouteStart.xml

fix for #484 - code completion popping up at wrong locations

---

camel-idea-plugin/pom.xml
camel-idea-plugin/src/main/java/org/apache/camel/idea/annotator/CamelBeanMethodAnnotator.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/contributor/CamelJavaReferenceContributor.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/completion/extension/CamelJavaBeanReferenceSmartCompletion.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/extension/CamelIdeaUtilsExtension.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/reference/CamelBeanReferenceContributor.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/service/extension/camel/JavaCamelIdeaUtils.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/service/extension/camel/XmlCamelIdeaUtils.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/util/CamelIdeaUtils.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/util/JavaClassUtils.java
camel-idea-plugin/src/main/java/org/apache/camel/idea/util/JavaMethodUtils.java
camel-idea-plugin/src/main/resources/META-INF/plugin.xml
camel-idea-plugin/src/test/java/org/apache/camel/idea/CamelLightCodeInsightFixtureTestCaseIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/annotator/CamelJSonPathAnnotatorTestIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/completion/JavaCamelBeanReferenceSmartCompletionTestIT.java
camel-idea-plugin/src/test/java/org/apache/camel/idea/reference/CamelBeanMethodReferenceTest.java
camel-idea-plugin/src/test/resources/testData/completion/method/CompleteJavaBeanTestData.java
camel-idea-plugin/src/test/resources/testData/completion/method/CompleteJavaSpringComponentBeanRouteTestData.java
camel-idea-plugin/src/test/resources/testData/completion/method/CompleteJavaSpringComponentBeanTestData.java
camel-idea-plugin/src/test/resources/testData/completion/method/CompleteJavaSpringRepositoryBeanRouteTestData.java
camel-idea-plugin/src/test/resources/testData/completion/method/CompleteJavaSpringRepositoryBeanTestData.java
camel-idea-plugin/src/test/resources/testData/completion/method/CompleteJavaSpringServiceBeanRouteTestData.java
camel-idea-plugin/src/test/resources/testData/completion/method/CompleteJavaSpringServiceBeanTestData.java

This extend the bean code completion and find usage with support also for Spring beans

Springbean support

---

camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/extension/camel/JavaCamelIdeaUtils.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/util/JavaClassUtils.java
camel-idea-plugin/src/main/resources/META-INF/plugin.xml
camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/JavaCamelBeanReferenceSmartCompletionTestIT.java
camel-idea-plugin/src/test/java/com/github/cameltooling/idea/reference/CamelBeanMethodReferenceTest.java
camel-idea-plugin/src/test/resources/testData/completion/method/CompleteJavaBeanRoute10TestData.java
camel-idea-plugin/src/test/resources/testData/completion/method/CompleteJavaBeanRoute11TestData.java
camel-idea-plugin/src/test/resources/testData/completion/method/CompleteJavaBeanRoute9TestData.java
camel-idea-plugin/src/test/resources/testData/completion/method/CompleteJavaSpringServiceBeanTestData.java

- Fix an NP caused when lookup a bean when it's name was empty

Add support for using static string name as bean reference.

---

build.gradle
camel-idea-plugin/build.gradle
camel-idea-plugin/src/main/resources/META-INF/plugin.xml
camel-idea-plugin/src/test/java/com/github/cameltooling/idea/CamelLightCodeInsightFixtureTestCaseIT.java
camel-idea-plugin/src/test/resources/testData/documentation/javaClassQuickNavigateInfo.html

- Update version
- Update plugin.xml with change log

Release a new version.

---

build.gradle
camel-idea-plugin/src/main/resources/META-INF/plugin.xml

- Update plugin.xml for next version

- Update the bump version and set in snapshot mode

---

camel-idea-plugin/build.gradle
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/completion/endpoint/CamelSmartCompletionEndpointOptions.java
camel-idea-plugin/src/main/resources/META-INF/plugin.xml
gradle.properties

I'm a little unsure on how to complete this but I followed the guidelines and updated some resources and fixed the AllIcons compilation error.
If I have missed something or done wrong, please let me know and Iäll fix it

#545 Support for IntelliJ IDEA 2020.1

---

camel-idea-plugin/src/main/resources/META-INF/plugin.xml

This mainly contains Camel and Intellij API changes that had to be dealt with. Unfortunately, quite a few unit tests are failing, but the corresponding plugin functionality seems to be working well. Sending this PR now because I think a lot of people can make use of it while we work on getting some of the tests updated and working. 
Resolves #576, Resolves #560, Resolves #532.

Update to Camel 3.9.0 & Intellij 2021.1

---

camel-idea-plugin/src/main/resources/META-INF/plugin.xml
gradle.properties

Upgraded to Camel 3.11.1

---

camel-idea-plugin/src/main/resources/META-INF/plugin.xml
gradle.properties

Upgraded to Camel 3.11.1 (updated since-build to 212)

Upgraded to Camel 3.11.1 (updated since-build to 212)

---

readme.md

renaming the default branch in gitHub Web UI from `master` to `main` should be done before merging this PR

Migrate reference from master to main branch #625

---

camel-idea-plugin/src/main/java/com/github/cameltooling/idea/extension/CamelIdeaUtilsExtension.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerSession.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/ContextAwareDebugProcess.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/breakpoint/CamelBreakpoint.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/breakpoint/CamelBreakpointType.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/stack/CamelMessageInfo.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/extension/camel/JavaCamelIdeaUtils.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/extension/camel/XmlCamelIdeaUtils.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/util/CamelIdeaUtils.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/util/JavaClassUtils.java

- Improved Java DSL support per Issue #650;
- Dedicated run configurations are no longer required (however, SpringBoot apps must run with `-Dspring-boot.run.fork=false`;
- Resolves #649;
- Resolves #645;

Java DSL support

---

camel-idea-plugin/src/main/java/com/github/cameltooling/idea/language/CamelLanguages.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerRunner.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerSession.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/breakpoint/CamelBreakpointType.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/ui/CamelExpressionParameters.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/ui/CamelSpringBootRunnerConfPanel.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/extension/camel/JavaCamelIdeaUtils.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/extension/camel/XmlCamelIdeaUtils.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/extension/camel/YamlCamelIdeaUtils.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/util/CamelIdeaUtils.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/util/IdeaUtils.java
camel-idea-plugin/src/main/resources/META-INF/plugin.xml

Yaml support

---

camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/extension/camel/YamlCamelIdeaUtils.java

Resolves #657

---

camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebugProcess.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerRunner.java
camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerSession.java
camel-idea-plugin/src/main/resources/META-INF/dataSonnetInjections.xml
camel-idea-plugin/src/main/resources/META-INF/org.apache.camel-intelliLang.xml
camel-idea-plugin/src/main/resources/META-INF/plugin.xml

- DataSonnet Language Injection;
- camel-debug detection in classpath.

Minor improvements

---

.github/workflows/ci-build.yaml

The goal of this PR is to upload also the log file of the test for further investigations

Add test logs to the list of CI artifacts

---

camel-idea-plugin/src/main/java/com/github/cameltooling/idea/service/CamelService.java

fixes #703 
The service `CamelService` is not thread-safe which causes issues of type `ConcurrentModificationException` and which could lead to race condition issues
* Protect access to shared fields with synchronized blocks using the same mutex
* Provide only a copy of library names to ensure the thread-safety outside the class
* Protect the code scanning of the libraries of a module in a synchronized to ensure that all concurrent accesses on project libraries will get a consistent state
* Make all notifications volatile as there is no need to block the threads for such fields.
* Rename `slf4japiLibrary` to `slf4jApiLibrary` to keep the expected case (not related to the initial issue)

Ref #703 - Make CamelService thread-safe

---

camel-idea-plugin/src/main/java/com/github/cameltooling/idea/runner/debugger/CamelDebuggerSession.java

fixes #831 
The problem described in https://github.com/camel-tooling/camel-idea-plugin/issues/820 also occurs when the routes are directly in the sources of the project launching Camel. In other words, when calling `dumpRoutesAsXml` on a Quarkus runtime, for XML and YAML routes, the attribute `sourceLocation` is of type `file:src/main/resources/routes/camel-routes.xml` instead of being into `target/classes`.
* Uses the same kind of fix as the one used for #820 but for file path
* Replaces `"src/main/resources/"` with a static field to avoid duplications

Ref #831: Make the debugger accepts relative path to source directory

---

.github/workflows/ci-build.yaml
build-all.sh
build.sh

The build takes too long, let's try to parallelize the best we can.
* Add the versions of the plugin to test in the matrix
* Add a script to test against a specific version

Reduce the build time

---

camel-idea-plugin/src/main/java/com/github/cameltooling/idea/intention/CamelAddEndpointIntention.java

fixes #869 
If we try to display the add endpoint popup too quickly we can get an `IntentionPreviewUnsupportedOperationException`.
* Ensure that the editor is in the right state before eventually creating the popup
* Use the benefits of the builder pattern to create the popup for clarity (not related to the initial issue)

Ref #869: Prevent exception when creating the add endpoint popup

---

camel-idea-plugin/src/main/resources/META-INF/plugin.xml
camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/JavaEndpointSmartCompletionTestIT.java
camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/PropertyEndpointSmartCompletionTestIT.java
camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/XmlEndpointSmartCompletionTestIT.java
camel-idea-plugin/src/test/java/com/github/cameltooling/idea/completion/YamlEndpointSmartCompletionTestIT.java
gradle.properties

fixes #963 
A new minor version of Camel has been released so let's upgrade it in the plugin
* Upgrade the version of Camel, Camel Quarkus, and Camel Karaf to the latest version
* Fix unit tests consequently

Ref #963: Upgrade to Camel 4.3, Camel Quarkus 3.6 and Camel Karaf 3.22

---

gradle.properties

Ref #1030: Upgrade to Camel 4.7, Camel Quarkus 3.12 and Camel Kamelet 4.7

---

build.gradle

https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html#open-end-compatibility

Implementing "Open-End Compatibility"

---

src/main/java/com/github/cameltooling/idea/documentation/CamelDocumentationProvider.java

Remove redundant newlines in Tooltip before description
